CREATE TABLE DB2UDB3.CD_IO_SENDTASK_LOG ( 
ID DECIMAL(10,0) NOT NULL, 
TASK_TYPE DECIMAL(2,0) NOT NULL, 
SUBPACKAGE_ID DECIMAL(10,0) NOT NULL, 
PLAN_SEND_TIME TIMESTAMP, 
SEND_TIME TIMESTAMP, 
END_TIME TIMESTAMP, 
SRC_DIR VARCHAR(255), 
STATUS DECIMAL(2,0), 
RESULT DECIMAL(2,0), 
ERR_CODE VARCHAR(100), 
ERR_CAUSE VARCHAR(255),
SEQNUM VARCHAR(50),
RECORD_NUM DECIMAL(10,0),
RESPCODE VARCHAR(15)
);
create sequence "DB2UDB3"."CD_IO_SENDTASK_LOG_SEQ" as INTEGER start with 1 increment by 1 no minvalue no maxvalue no cycle cache 20 no order;